site_name: hvanbelle my-project docs
nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: primary
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  navigation_depth: 2